import {useEffect,useMemo,useState} from 'react'; import {Activity, AlertTriangle, CheckCircle2, Clock3, Plus, ShieldCheck, Sparkles} from 'lucide-react'; import {API,request} from './api';

type Incident={id:number;title:string;description:string;severity:string;status:string;service:string;logs:string;ai_summary?:string;ai_root_cause?:string;ai_recommendations?:string;created_at:string};
const demo={email:'admin@sentinel.local',password:'Admin@123'};
function App(){const [token,setToken]=useState(localStorage.getItem('token')); const [incidents,setIncidents]=useState<Incident[]>([]); const [selected,setSelected]=useState<Incident|null>(null); const [showForm,setShowForm]=useState(false); const [live,setLive]=useState(false); const [form,setForm]=useState({title:'',service:'payments-api',severity:'high',description:'',logs:''});
 const load=async()=>{try{setIncidents(await request('/api/v1/incidents'))}catch(e){}};
 useEffect(()=>{if(token) load();},[token]);
 useEffect(()=>{if(!token)return; const ws=new WebSocket(API.replace(/^http/,'ws')+'/api/v1/incidents/ws/incidents'); ws.onopen=()=>setLive(true); ws.onclose=()=>setLive(false); ws.onmessage=()=>load(); return()=>ws.close()},[token]);
 const stats=useMemo(()=>({total:incidents.length,open:incidents.filter(x=>x.status==='open').length,critical:incidents.filter(x=>x.severity==='critical').length,resolved:incidents.filter(x=>x.status==='resolved').length}),[incidents]);
 async function login(){const r=await request('/api/v1/auth/login',{method:'POST',body:JSON.stringify(demo)});localStorage.setItem('token',r.access_token);setToken(r.access_token)}
 async function create(){await request('/api/v1/incidents',{method:'POST',body:JSON.stringify(form)});setShowForm(false);setForm({title:'',service:'payments-api',severity:'high',description:'',logs:''});load()}
 async function analyze(id:number){const r=await request(`/api/v1/incidents/${id}/analyze`,{method:'POST'});setSelected(r);load()}
 async function update(id:number,status:string){await request(`/api/v1/incidents/${id}`,{method:'PATCH',body:JSON.stringify({status})});load();if(selected?.id===id)setSelected({...selected,status})}
 if(!token)return <main className="login"><div className="card login-card"><div className="logo"><ShieldCheck/></div><h1>Sentinel<span>AI</span></h1><p>Real-time incident intelligence platform</p><button onClick={login}>Enter Demo Dashboard</button><small>Demo: admin@sentinel.local / Admin@123</small></div></main>;
 return <div className="app"><header><div className="brand"><ShieldCheck/><b>SentinelAI</b><span>Incident Command Center</span></div><div className="live"><i className={live?'on':''}></i>{live?'Live':'Offline'}</div></header><section className="hero"><div><p className="eyebrow">OPERATIONS OVERVIEW</p><h2>Stay ahead of incidents.</h2><p>Monitor, investigate and resolve service disruptions with AI-assisted incident intelligence.</p></div><button className="primary" onClick={()=>setShowForm(true)}><Plus size={18}/> New Incident</button></section>
 <section className="stats"><Stat icon={<Activity/>} label="Total incidents" value={stats.total}/><Stat icon={<AlertTriangle/>} label="Open" value={stats.open}/><Stat icon={<Clock3/>} label="Critical" value={stats.critical}/><Stat icon={<CheckCircle2/>} label="Resolved" value={stats.resolved}/></section>
 <section className="content"><div className="card table"><div className="card-head"><div><h3>Incident Feed</h3><p>Real-time service events</p></div><span className="pill">{incidents.length} records</span></div>{incidents.length===0?<div className="empty">No incidents yet. Create one to test the workflow.</div>:incidents.map(i=><button className="row" key={i.id} onClick={()=>setSelected(i)}><div className={'sev '+i.severity}>{i.severity[0].toUpperCase()}</div><div className="row-main"><b>{i.title}</b><span>{i.service} · {new Date(i.created_at).toLocaleString()}</span></div><span className={'status '+i.status}>{i.status}</span></button>)}</div>
 <div className="card detail">{selected?<><div className="card-head"><div><p className="eyebrow">INCIDENT #{selected.id}</p><h3>{selected.title}</h3></div><span className={'status '+selected.status}>{selected.status}</span></div><p>{selected.description||'No description provided.'}</p><div className="meta"><span>Service <b>{selected.service}</b></span><span>Severity <b>{selected.severity}</b></span></div><h4>Log evidence</h4><pre>{selected.logs||'No logs attached.'}</pre><div className="ai-box"><div className="ai-title"><Sparkles size={17}/> AI Investigation</div>{selected.ai_summary?<><p><b>Summary:</b> {selected.ai_summary}</p><p><b>Root cause:</b> {selected.ai_root_cause}</p><p><b>Recommendations:</b> {selected.ai_recommendations}</p></>:<p>Run AI analysis to generate an investigation summary and recommended next steps.</p>}<button onClick={()=>analyze(selected.id)} className="ai-btn"><Sparkles size={16}/> Analyze with SentinelAI</button></div><div className="actions">{selected.status!=='resolved'&&<button onClick={()=>update(selected.id,'resolved')}>Mark resolved</button>}</div></>:<div className="empty detail-empty">Select an incident to investigate.</div>}</div></section>
 {showForm&&<div className="overlay"><div className="modal"><h3>Create Incident</h3><input placeholder="Incident title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Service name" value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option>critical</option><option>high</option><option>medium</option><option>low</option></select><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><textarea placeholder="Paste relevant logs..." value={form.logs} onChange={e=>setForm({...form,logs:e.target.value})}/><div className="modal-actions"><button onClick={()=>setShowForm(false)}>Cancel</button><button className="primary" onClick={create}>Create incident</button></div></div></div>}</div>}
function Stat({icon,label,value}:{icon:any;label:string;value:number}){return <div className="card stat"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}; export default App;
